### PR TITLE
Ongoing notification

### PR DESCRIPTION
**Pull request by simonesestito**
Avoid dismiss the notification because an error. To close it, you can use the appropriate button.

### CODE REVIEW

**Comment by tananaev** [comment]
I'm not convinced that it's a good idea. Some people might find it annoying that you can remove it with a swipe.

**Comment by simonesestito** [comment]
I found the swipe annoying, so I forked the repo and "fixed" it myself. I don't know what other people want

**Comment by tananaev** [comment]
I'll watch for feedback from people and maybe merge it in future. Thanks for pull request.

**Comment by hmueller01** [comment]
I find it annoying that calculator notification goes away with "clean all". So I forked the repo and added `.setOngoing(true)` to the notification builder. I havn't seen this pull before and was about to write a pull by myself. But @simonesestito 's solution is much more sophisticated and I vote for that pull!

**Comment by tananaev** [comment]
If we can make it configurable, I'm happy to accept this change.

**Pull request closed without merging**
